# docker-compose.yml
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:ro  # Read-only mount for safety
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - DEBUG=1  # Remove in production
    command: poetry run python main.py
    restart: unless-stopped